### ISSUE TITLE
[Babel Problems with vpack] Try running vpack on example/ui/index

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-hub#116]
problem is, the wsClient in the webocket module stops workng -- we need a solution for this

**Comment by DanilloCorvalan** [comment]
![screen shot 2016-03-14 at 14 01 20](https://cloud.githubusercontent.com/assets/1444981/13745325/b16e8258-e9ed-11e5-9b94-aeda160203a8.png)
@jimdebeer I don't get errors on the bundling phase of webpack. The only error I get is the one I placed above. Is that the problem ?

**Comment by jimdebeer** [comment]
thats the problem, try running it without and with babel

**Comment by jimdebeer** [comment]
problem is nested modules that don't need parsing -- we need a way to check for this is guess, browserify has this nice transformers field for it -- else ignore it, but we can think of something perhaps -- we can also build a blacklist in vpack although thats my least favourite solution

also read up on https://gist.github.com/substack/68f8d502be42d5cd4942 this pretty much puts the finger in the open wound

**Comment by DanilloCorvalan** [comment]
@jimdebeer There is a way to ignore modules in webpack. I can export that to vpack

**Comment by jimdebeer** [comment]
yeah its a bit of shitty solution though -- we have to add every npm module that will fail in this way to that ignore field, its also not that i don't need to module in the build right? it just that i cant have it in the wpack babel loader since it messes everything up

**Comment by DanilloCorvalan** [comment]
It's also possible to ignore modules for specific loaders, but it will include them on the build

**Comment by jimdebeer** [comment]
ok is it possible to try to find a better solution first? this is the worst solution we have ofc

**Comment by jimdebeer** [comment]
example what we can do is read out the browserify transforms fields and map them to wepack loaders -- this way we can replace stuff later -- but i think this is pretty much nessecary and will increase your speed as well

**Comment by jimdebeer** [comment]
```
"browserify": {
    "transform": [ "brfs" ]
  }
```

read this from the pckg.json of nested modules apply loaders based on transforms and we map transforms to webpack -- may need to replace webpack again with browserify later but we can worry about that -- later

**Comment by jimdebeer** [comment]
@youzi what do you think?

**Comment by jimdebeer** [comment]
no more vpack!
