### ISSUE TITLE
[Adapter] Connect

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-hub#13]
connect needs to fire disconnect per upstream?

**Comment by ninjatux** [comment]
yeah, what we can do is allowing the hub to send a `disconnect` event to all its downstream clients and let them gracefully disconnect. Once the clients are disconnected the hub will emit an event like `downstream_empty` or something similar to inform that the process can be killed.

in the `disconnect` message the hub can specify a new URL where to connect.

**Comment by ninjatux** [comment]
maybe is better to have a `shutdown` method on the hub which sends a disconnect message to clients and let them manage it. We can either send a new URL with the shutdown message, letting the clients decide which hub is better based on their internal list of hubs or both
