### ISSUE TITLE
[Connection] Reconnecting strategies

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-hub#15]
some hard things we learned
- reconnecting is tricky on native ios (have to force reconnect on resume event)
- reconnecting is tricky on android
- some 3g networks only allow port 443 or 80 to communicate over never use weird ports!

**Comment by jimdebeer** [comment]
we need to be able to inject multiple protocols to be able to handle this

**Comment by ninjatux** [comment]
we can force a disconnect and then a new connect on those events. this issue should be tackled after #36

**Comment by jimdebeer** [comment]
yeah we can then sue those methods for switching between hubs as well
