### ISSUE TITLE
[Connection] HTTP Requests

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/brisky-hub#16]
We need an utility which is able to perform HTTP requests to a given URL.

COS:
- It must work for both Node and Browser
- It must support all type of HTTP methods

**Comment by ninjatux** [comment]
Was thinking about this implementation and how it could affect who will use this.

After some thoughts I believe that this kind of communication client should have a simple interface that has to be the same for all the clients, or at least different in the extra arguments. Something like `send(data)`

The config will be given by the adapter through properties (eg: `this.http.url`) and checked by the clients implementation of the `send` method

Every client will be able to expose extra method if needed (eg: `redis.connect()`)

To me this kind of interface is easier to understand, what do you think @jimdebeer?

**Comment by jimdebeer** [comment]
yes the .send is smart since this part will be called by the upstream base (and all deeper objects) simple interface is perfect since this is the only place where we use it we don't need this part to be an observable -- only upstream (if i lets say change the url of an upstream i want it to do stuff)

**Comment by jimdebeer** [comment]
so yes simple for protocols, more complex when moving up ( Hub -- Upstream --- Adapter -- Protocol )
protocol is super low

**Comment by jimdebeer** [comment]
this will become the same as "connection" #18

**Comment by ninjatux** [comment]
not needed anymore after the redesign
