### ISSUE TITLE
[Adapter] Spec it well

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-hub#2]
adapaters are used for hub to hub communication

![image](https://cloud.githubusercontent.com/assets/5682524/10455365/2a6bc752-71bb-11e5-933d-23fdb3a22039.png)

methods
- subscribe
- unsubscribe
- write
- push
- connect (needs to accept a clientid field, also needs a reconnect / tries option (but later))
- disconnect

**Comment by jimdebeer** [comment]
we need to be able to pass an instanceID (e.g. user.token) in everymethod

**Comment by ninjatux** [comment]
and in every method if no **instanceID** is passed we can create one and return it

**Comment by jimdebeer** [comment]
adapter has live on the upstream level (multiple upstreams per hub)

**Comment by jimdebeer** [comment]
protocols have to be injectable

**Comment by jimdebeer** [comment]
``` javascript
module.exports = new Hub({
  adapter: {
    inject: require('../../lib/adapter/websocket'),
    on: {
      connection () {
        console.log('\n',
        uuid.green.bold,
        'connected',
        '\n    url:', this.val
        )
      },
      error (err) {
        console.log(err)
      },
      close () {
        console.log('o noes!'.red)
      },
      listens (data) {
        console.log(
          '\n',
          uuid.green.bold,
          'listening',
          '\n    protocol:', data,
          '\n    port:', this.listens.val
        )
      }
    }
  },
  clients: {
    on: {
      property: require('./dev').clients
    }
  },
  on: {
    data: {
      performance: require('./dev').performance,
      log: require('./dev').data
    }
  }
})
```

example of a server can be found in examples/basic

**Comment by jimdebeer** [comment]
https://github.com/juliangruber/reconnect-core  -- may be a good idea for reconnection

**Comment by ninjatux** [comment]
testing the modules [reconnect-core](https://github.com/juliangruber/reconnect-core) and [retry](https://www.npmjs.com/package/retry)

**Comment by jimdebeer** [comment]
need to check for different adapters on different instances
