### ISSUE TITLE
Hub doesn't remove client when connection is closed

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/brisky-hub#25]
###### The problem

If a client connects to the HUB and then close its connection the client is not removed from the list of clients.
###### How to reproduce
1. run the server `examples/browser/server.js`
2. open `examples/browser/client.js`
3. refresh the browser page a couple of times (for every refresh the HUB creates a new UUID and then connects to the server)
4. send a message to the server typing something in `TextField2`
5. look at logs on server, it tries to propagate the message to all the clients in its bucket
###### Solution

We need to find a way to associate clients with connections

**Comment by jimdebeer** [comment]
on it!
