### ISSUE TITLE
[bug] Strange behaviour for connections

### ISSUE THREAD

**Issue by ninjatux** [vigour-io/brisky-hub#44]
I didn't checked properly but I guess we have a bug in connection or somewhere else where we call it. It occurs when we play with `adapters` keeping changing their value for creating a ws client.

eg:

``` js
var client = new Hub({
  adapter: {
    inject: require('../../lib/adapter/websocket'),
    on: {
      error (err, ev) {
        console.log('-- C1 Error ', err.message, err.stack)
      }
    }
  }
})

setInterval(() => { client.adapter.val = 3033 }, 300)
setInterval(() => { client.adapter.val = 3031 }, 330)
```

From the logs we can easily see that we create multiple WS clients for the same adapter client which is wrong.

**Comment by jimdebeer** [comment]
we need to delete the old connection on overwrite I geuss, great test btw ;)
